# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    # Creamos diferentes estrategias para que funcione en windows, ubuntu y mac os:
    strategy:
      matrix:
        agent: ['windows-latest','ubuntu-latest','macos-latest']
    runs-on: ${{matrix.agent}}
    
    # Se le pone a cada una de las integraciones un nombre identificativo, utilizando la variable de la matriz:
    name: Integration in ${{matrix.agent}}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
            
      - name: Setup .NET5
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '5.0.x'            
      - name: Clean
        run: dotnet clean "ApiRestfulSample.sln" --configuration Release && dotnet nuget locals all --clear
      - name: Build with dotnet
        run: dotnet build "ApiRestfulSample.sln"
      #- name: Test with dotnet
      #- run: dotnet test "ApiRestfulSample.sln" #Para que funcionaran correctamente los test, habría que moquear el HttpClient
